version: '3'
services:
  gatewayapi:
    image: mediablog/gatewayapi
    build:
      context: ./src/MediaBlog
      dockerfile: Gateway.API/Dockerfile
    ports:
      - 32770:8080
      - 32771:8081
    environment:
      ConnectionStrings__Redis: redis:6379
      RabbitMQ__Hostname: rabbitmq
      RabbitMQ__Username: $RABBITMQ_USER
      RabbitMQ__Password: $RABBITMQ_PWD
      PostsApiUrl: http://postsapi:8080
    depends_on:
      rabbitmq:
        condition: service_healthy

  postsapi:
    image: mediablog/postsapi
    build:
      context: ./src/MediaBlog
      dockerfile: Posts.API/Dockerfile
    environment:
      ConnectionStrings__PostsDB: Server=sqlserver;Initial Catalog=PostsDB;User Id=sa;Password=$MSSRV_PWD;TrustServerCertificate=True
      ConnectionStrings__Redis: redis:6379
      RabbitMQ__Hostname: rabbitmq
      RabbitMQ__Username: $RABBITMQ_USER
      RabbitMQ__Password: $RABBITMQ_PWD
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:$RABBITMQ_VER
    ports:
      - 15672:15672
    volumes:
        - ./volumes/rabbitmq/data/:/var/lib/rabbitmq/
        - ./volumes/rabbitmq/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_PWD
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis:$REDIS_VER

  sqlserver:
    image: mcr.microsoft.com/mssql/server:$MSSRV_VER
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: $MSSRV_PWD
    volumes:
      - ./volumes/sqlserver:/var/opt/mssql/data